# Generated by Django 5.0.14 on 2026-05-24 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_source', models.CharField(max_length=255, verbose_name='Vendor / Source')),
                ('task_name', models.CharField(max_length=255, verbose_name='Task Name')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('category', models.CharField(choices=[('printer', 'Printer'), ('consumables', 'Consumables')], default='printer', max_length=50, verbose_name='Category')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=50, verbose_name='Priority')),
                ('status', models.CharField(choices=[('to_do', 'To Do'), ('not_started', 'Not Started'), ('gathering_info', 'Gathering Information'), ('in_progress', 'In Progress'), ('under_validation', 'Under Validation'), ('deployed_stage', 'Deployed to Stage'), ('deployed_prod', 'Deployed to Prod'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='not_started', max_length=50, verbose_name='Status')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Problem / Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deployment_link', models.URLField(blank=True, null=True, verbose_name='Deployment Link')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task', verbose_name='Task')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
