# Generated by Django 5.0.14 on 2026-05-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_update_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('under_validation', 'Under Validation'), ('deployed_stage', 'Deployed to Stage'), ('deployed_prod', 'Deployed to Prod'), ('done', 'Done'), ('blocked', 'Blocked')], default='to_do', max_length=50, verbose_name='Status'),
        ),
    ]
